---
sidebar: sidebar 
permalink: get-started/before_get_started.html 
keywords:  
summary:  
---
= Antes de empezar
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede prepararse rápidamente para empezar a utilizar la API REST de Astra Control revisando los pasos que se describen a continuación.

.Revisar los conceptos e implementación de REST
Asegúrese de revisarlo link:../rest-core/rest_web_services.html["Implementación básica de REST"] Para obtener información sobre conceptos DE REST y detalles sobre cómo se diseña la API ASTRA Control REST.

.Tener credenciales de cuenta de Astra
Necesitará credenciales de Astra para iniciar sesión en la interfaz de usuario web de Astra y generar un token de API. Con Astra Control Center, puede gestionar estas credenciales localmente. Con Astra Control Service, las credenciales de cuenta se mantienen mediante el servicio *Auth0*.

.Obtenga más información
Debe conocer los recursos de información adicionales que se sugieren en la link:../information/additional_resources.html["Recursos adicionales"].
